# Generated by Django 4.1.6 on 2023-02-14 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0001_initial"),
        ("groups", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pets",
            new_name="Pet",
        ),
    ]
