# Generated by Django 4.1.6 on 2023-02-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_pets_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("NI", "Not Informed")],
                default="Not informed",
                max_length=20,
            ),
        ),
    ]
