# Generated by Django 4.1.6 on 2023-02-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0003_remove_trait_pets_trait_created_at"),
        ("pets", "0007_alter_pet_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(to="traits.trait"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.FloatField(),
        ),
    ]
