# Generated by Django 4.1.6 on 2023-02-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0002_alter_group_scientific_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
